# -*- coding: utf-8 -*-
"""SKIN DISEASE PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFl_4hcTWAp0IF_R5g1UNtBvBKH0M_Tu

# Step1: Imports and Device Setup
"""

# ================================
# 📌 Step 1: Imports & Device Setup
# ================================

# System & utility
import os
import random
import numpy as np
from tqdm import tqdm

# PyTorch core
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split

# Torchvision (datasets, transforms, pretrained models)
from torchvision import datasets, transforms, models

# timm (for EfficientNet variants & other modern models)
import timm

# Sklearn (metrics & class weights)
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Device setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"📦 Using device: {device}")

# Reproducibility (set random seeds)
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)

"""# Step 2: Paths & Basic Config"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

import os
import zipfile

# Make hidden kaggle folder
os.makedirs("/root/.kaggle", exist_ok=True)

# Move kaggle.json
!mv /content/drive/MyDrive/MINI_PROJECT_25/kaggle.json /root/.kaggle/

# Set correct permissions
!chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d pacificrm/skindiseasedataset
# Unzip
with zipfile.ZipFile("skindiseasedataset.zip", 'r') as zip_ref:
    zip_ref.extractall("SkinDisease")

# Check structure
!ls SkinDisease

!mv /content/SkinDisease/SkinDisease /content/drive/MyDrive/MINOR_PROJECT_25

# ================================
# 📌 Step 2: Paths & Basic Config
# ================================

# Define base project path inside Google Drive
BASE_PATH = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease"
# Create project directories if not exist
os.makedirs(BASE_PATH, exist_ok=True)
os.makedirs(os.path.join(BASE_PATH, "models"), exist_ok=True)   # for saving models
os.makedirs(os.path.join(BASE_PATH, "results"), exist_ok=True)  # for saving plots/reports

# Dataset directories (update these according to where you store the dataset in Drive)
train_dir = os.path.join(BASE_PATH, "train")
test_dir  = os.path.join(BASE_PATH, "test")

print(f"📂 Training data: {train_dir}")
print(f"📂 Testing data:  {test_dir}")

# =========================
# Hyperparameters
# =========================
IMAGE_SIZE = 224        # input size for all models
BATCH_SIZE = 32         # adjust if OOM
LEARNING_RATE = 1e-4
EPOCHS = 40             # can tune later
PATIENCE = 5            # early stopping

print(f"✅ Config set | Image size={IMAGE_SIZE}, Batch size={BATCH_SIZE}, LR={LEARNING_RATE}, Epochs={EPOCHS}")

"""# Step 3: Data Transforms

---


"""

# Train transforms (more augmentation for robustness)
train_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])   # ImageNet pretrained normalization
])

# Validation/Test transforms (minimal augmentation)
test_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

"""# Step 4 Datasets & Loaders"""

# ================================
# 📌 Step 4: Datasets & DataLoaders (Kaggle style)
# ================================

from torchvision import datasets

# Load datasets
train_dataset = datasets.ImageFolder(train_dir, transform=train_transform)
test_dataset  = datasets.ImageFolder(test_dir, transform=test_transform)

# Create loaders (validation will be created later)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0) # Set num_workers to 0
test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0) # Set num_workers to 0

# Class names
class_names = train_dataset.classes
print(f"✅ Loaded {len(train_dataset)} training and {len(test_dataset)} test images")
print(f"📚 Number of classes: {len(class_names)} → {class_names}")

"""# Step 5: Enhanced EDA"""

# ================================
# 📌 Step 5: EDA - Class Distribution (Optimized Kaggle Style)
# ================================

import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# Count images per class
label_counts = Counter(train_dataset.targets)

# Plot class distribution
plt.figure(figsize=(12, 5))
sns.barplot(
    x=[class_names[i] for i in label_counts.keys()],
    y=list(label_counts.values()),
    palette="viridis"
)
plt.xticks(rotation=90)
plt.title("Class Distribution in Training Set")
plt.ylabel("Number of Images")
plt.xlabel("Class Name")
plt.tight_layout()
plt.show()

# ================================
# 📌 Step 5: Visual Check of Sample Images
# ================================

def visualize_samples(dataset, n=5):
    """
    Display n sample images from the dataset with class names and shape info.
    """
    fig, axes = plt.subplots(1, n, figsize=(15, 3))

    for i in range(n):
        image, label = dataset[i]

        # Convert tensor to numpy for plotting (denormalize if needed)
        img_display = image.permute(1, 2, 0).numpy() * 0.5 + 0.5  # Kaggle style normalization
        img_display = np.clip(img_display, 0, 1)

        axes[i].imshow(img_display)
        axes[i].set_title(f"{class_names[label]}\n{image.shape}")
        axes[i].axis("off")

    plt.tight_layout()
    plt.show()

# Display 5 sample images from training set
visualize_samples(train_dataset, n=5)

# ================================
# 📌 Step 5 (Optimized): Quick Image Shape Check
# ================================

from collections import Counter

shapes = [train_dataset[i][0].shape for i in range(50)]  # check only first 50 images
shape_counts = Counter(shapes)

print("🖼️ Sample image shapes in dataset:", shape_counts)

"""# step 6 Compute Weighted Loss"""

# ================================
# 📌 Step 6: Class Imbalance Handling / Weighted Loss
# ================================

from sklearn.utils.class_weight import compute_class_weight
import torch.nn as nn
import torch

# Get training labels
labels = train_dataset.targets

# Compute class weights (balanced)
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(labels),
    y=np.array(labels)
)

# Convert to tensor and move to device
class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

# Define criterion with weighted loss
criterion = nn.CrossEntropyLoss(weight=class_weights)

print(f"📊 Class weights tensor: {class_weights}")

"""# Step 7: Model Definition + Optimizer"""

# ================================
# 📌 Step 7: Model Definitions + Optimizers + Schedulers
# ================================

import timm
import torch.nn as nn
import torch.optim as optim
from torchvision import models

# -------------------------
# num_classes from dataset
# -------------------------
num_classes = len(class_names)
print(f"📚 Number of classes: {num_classes}")

# -------------------------
# EfficientNet-B0
# -------------------------
efficientnet_b0 = timm.create_model('efficientnet_b0', pretrained=True, num_classes=num_classes)
efficientnet_b0 = efficientnet_b0.to(device)

optimizer_b0 = optim.Adam(efficientnet_b0.parameters(), lr=1e-3)
scheduler_b0 = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_b0, mode='max', patience=2, factor=0.3
)
print("✅ EfficientNet-B0 ready")

# -------------------------
# EfficientNet-B2
# -------------------------
efficientnet_b2 = timm.create_model('efficientnet_b2', pretrained=True, num_classes=num_classes)
efficientnet_b2 = efficientnet_b2.to(device)

optimizer_b2 = optim.Adam(efficientnet_b2.parameters(), lr=1e-3)
scheduler_b2 = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_b2, mode='max', patience=2, factor=0.3
)
print("✅ EfficientNet-B2 ready")

# -------------------------
# ResNet50
# -------------------------
resnet50 = models.resnet50(pretrained=True)
resnet50.fc = nn.Linear(resnet50.fc.in_features, num_classes)
resnet50 = resnet50.to(device)

optimizer_resnet = optim.Adam(resnet50.parameters(), lr=1e-3)
scheduler_resnet = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_resnet, mode='max', patience=2, factor=0.3
)
print("✅ ResNet50 ready")

# -------------------------
# DenseNet121
# -------------------------
densenet121 = models.densenet121(pretrained=True)
densenet121.classifier = nn.Linear(densenet121.classifier.in_features, num_classes)
densenet121 = densenet121.to(device)

optimizer_densenet = optim.Adam(densenet121.parameters(), lr=1e-3)
scheduler_densenet = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_densenet, mode='max', patience=2, factor=0.3
)
print("✅ DenseNet121 ready")

# -------------------------
# Verbose Simulation (Kaggle style)
# -------------------------
print("ℹ️ ReduceLROnPlateau schedulers configured. LR will reduce if metric doesn't improve for 2 epochs.")

"""# step 8 Split train_dataset into Train and Validation"""

# ================================
# 📌 Step 4b: Train/Validation Split (Fixed, Reproducible)
# ================================

from torch.utils.data import random_split, DataLoader
import torch

# Validation ratio
val_ratio = 0.1

# Compute split sizes
train_size = int((1 - val_ratio) * len(train_dataset))
val_size   = len(train_dataset) - train_size

# ✅ Use fixed generator seed so split is always the same
generator = torch.Generator().manual_seed(42)

# Split dataset (deterministic)
train_subset, val_subset = random_split(train_dataset, [train_size, val_size], generator=generator)

# DataLoaders
train_loader = DataLoader(train_subset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader   = DataLoader(val_subset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print(f"✅ Training samples: {len(train_subset)}, Validation samples: {len(val_subset)}")

"""# Full Training Code
Here is the full training loop with:

Class-weighted loss

Early stopping

Model checkpointing

Learning rate scheduler

Tracking and plotting learning curves

## RESNET 50
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models
from tqdm import tqdm
import copy, os

# ===========================
# Config
# ===========================
EPOCHS = 20
patience = 4
best_val_acc = 0
early_stop_counter = 0
save_path = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/models/best_resnet50.pth"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ===========================
# Load Pretrained ResNet50
# ===========================
resnet50 = models.resnet50(weights="IMAGENET1K_V1")
num_features = resnet50.fc.in_features
resnet50.fc = nn.Linear(num_features, num_classes)   # change final layer
resnet50 = resnet50.to(device)

# ===========================
# Loss, Optimizer, Scheduler
# ===========================
criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))
optimizer = optim.Adam(resnet50.parameters(), lr=1e-4)  # Adam is stable
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.3, patience=2)

# Logs
train_losses, val_losses, train_accuracies, val_accuracies = [], [], [], []

# ===========================
# Training Loop
# ===========================
for epoch in range(EPOCHS):
    # ---- Training ----
    resnet50.train()
    running_loss, correct, total = 0.0, 0, 0

    loop = tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Epoch {epoch+1}/{EPOCHS}")
    for _, (images, labels) in loop:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = resnet50(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        loop.set_postfix(train_loss=running_loss/total, train_acc=correct/total)

    train_loss = running_loss / total
    train_acc = correct / total
    train_losses.append(train_loss)
    train_accuracies.append(train_acc)

    # ---- Validation ----
    resnet50.eval()
    val_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:   # always full val set
            images, labels = images.to(device), labels.to(device)
            outputs = resnet50(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    val_loss /= total
    val_acc = correct / total
    val_losses.append(val_loss)
    val_accuracies.append(val_acc)

    scheduler.step(val_acc)  # since mode="max"

    print(f"Epoch {epoch+1}/{EPOCHS} "
          f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
          f"Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")

    # ---- Early Stopping ----
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_model_wts = copy.deepcopy(resnet50.state_dict())
        torch.save(resnet50.state_dict(), save_path)
        print(f"📌 Best model saved: {save_path}")
        early_stop_counter = 0
    else:
        early_stop_counter += 1
        if early_stop_counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

# Load best model
resnet50.load_state_dict(torch.load(save_path))
print(f"✅ Training complete. Best Val Acc = {best_val_acc:.4f}")

resnet50.load_state_dict(torch.load("/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/models/best_resnet50.pth", map_location=torch.device('cpu')))
resnet50.to(device)

"""Evaluate on Test Set"""

# ================================
# 📌 Step 10: Evaluate ResNet50 on Test Set
# ================================

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Put model in evaluation mode
resnet50.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = resnet50(images)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# ---- Classification Report ----
print("📊 Classification Report for ResNet50:")
print(classification_report(all_labels, all_preds, target_names=class_names))

"""Confusion Matrix"""

# ================================
# 📌 Step 11: Confusion Matrix - ResNet50
# ================================

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Put model in evaluation mode
resnet50.eval()
y_true = []
y_pred = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        outputs = resnet50(images)
        _, predicted = torch.max(outputs, 1)

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(predicted.cpu().numpy())

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(14, 12))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.title("Confusion Matrix on Test Set - ResNet50")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Misclassified Examples Visualization (ResNet50)"""

# ================================
# 📌 Misclassified Examples Visualization (ResNet50)
# ================================
import matplotlib.pyplot as plt
import torch.nn.functional as F

resnet50.eval()
misclassified = []

# Collect misclassified examples
with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = resnet50(images)
        probs = F.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        for i in range(len(labels)):
            if preds[i] != labels[i]:
                misclassified.append((
                    images[i].cpu(),
                    labels[i].item(),
                    preds[i].item(),
                    probs[i][preds[i]].item()
                ))

#  Sort by model confidence in wrong prediction
misclassified = sorted(misclassified, key=lambda x: x[3], reverse=True)

#  Use our dataset class names
class_names = train_dataset.classes

# ================================
# Plot Top Misclassified Examples
# ================================
plt.figure(figsize=(15, 10))
for idx, (img, true_label, pred_label, confidence) in enumerate(misclassified[:12]):
    plt.subplot(3, 4, idx + 1)

    # Denormalize (ImageNet mean/std)
    img = img.permute(1, 2, 0).numpy()
    img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]  # unnormalize
    img = img.clip(0, 1)

    plt.imshow(img)
    plt.title(
        f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.2f})",
        fontsize=9
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# Optional: Save figure for paper
plt.savefig("/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/figures/misclassified_resnet50.png")

"""Visualize Class-wise Performance with Per-Class ROC


"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np
import torch

resnet50.eval()
y_true = []
y_probs = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = resnet50(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())  # ensure it's from CPU

# Stack predictions & convert labels
y_probs = np.vstack(y_probs)  # shape: (num_samples, num_classes)
y_true = np.array(y_true)

# Binarize labels for one-vs-rest ROC
y_true_bin = label_binarize(y_true, classes=list(range(len(class_names))))
n_classes = y_true_bin.shape[1]

# Compute ROC curve and AUC for each class
fpr, tpr, roc_auc = {}, {}, {}
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot all ROC curves
plt.figure(figsize=(16, 12))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], lw=2,
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([-0.01, 1.01])
plt.ylim([-0.01, 1.01])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('Per-Class ROC Curves', fontsize=14)
plt.legend(loc="lower right", fontsize='small')
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

"""Per-Class Precision-Recall Curves"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from sklearn.metrics import precision_recall_curve, average_precision_score

# ======================
# 🔹 Get True Labels & Predicted Probabilities
# ======================
# y_true = ground-truth labels (ints)
# y_probs = predicted probabilities (after softmax), shape = [num_samples, num_classes]

num_classes = len(class_names)

# Convert to one-hot
y_true_binarized = label_binarize(y_true, classes=list(range(num_classes)))

# ======================
# 🔹 Plot Precision-Recall per class
# ======================
plt.figure(figsize=(12, 10))
colors = plt.cm.get_cmap("tab10", num_classes)

for i in range(num_classes):
    precision, recall, _ = precision_recall_curve(y_true_binarized[:, i], y_probs[:, i])
    ap_score = average_precision_score(y_true_binarized[:, i], y_probs[:, i])

    plt.plot(recall, precision, lw=2, color=colors(i),
             label=f"{class_names[i]} (AP = {ap_score:.2f})")

# ======================
# 🔹 Micro-average Precision-Recall
# ======================
precision_micro, recall_micro, _ = precision_recall_curve(y_true_binarized.ravel(),
                                                         y_probs.ravel())
ap_micro = average_precision_score(y_true_binarized, y_probs, average="micro")
plt.plot(recall_micro, precision_micro, linestyle='--', color='black',
         label=f"Micro-average (AP = {ap_micro:.2f})")

# ======================
# 🔹 Final Formatting
# ======================
plt.xlabel("Recall", fontsize=12)
plt.ylabel("Precision", fontsize=12)
plt.title("Per-Class Precision-Recall Curves", fontsize=14)
plt.legend(loc="best", fontsize="small")
plt.grid(True, linestyle="--", alpha=0.7)
plt.tight_layout()
plt.show()

"""Grad-Cam with PyTorch"""

import torch
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
import os

# ======================
# 🔹 Preprocessing (must match training transforms)
# ======================
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),   # adjust if trained on different size
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5],
                         std=[0.5, 0.5, 0.5])   # match your training normalization
])

# ======================
# 🔹 Select image
# ======================
# Option 1: Pick manually
#img_path = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/test/Rosacea/rosacea-104.jpeg"

# Option 2: Pick from misclassified list (example: first one)
img_tensor, true_label, pred_label, conf = misclassified[0]
img_np = ((img_tensor.permute(1,2,0).numpy() * 0.5) + 0.5) * 255
img_np = np.clip(img_np, 0, 255).astype(np.uint8)
img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)

# Load manually provided image
#img_bgr = cv2.imread(img_path)
#img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
#input_tensor = preprocess(Image.fromarray(img_rgb)).unsqueeze(0).to(device)

# ======================
# 🔹 Hook setup
# ======================
final_conv_layer = resnet50.layer4[-1]   # last block of ResNet50
gradients, activations = [], []

def backward_hook(module, grad_in, grad_out):
    gradients.append(grad_out[0].detach().cpu())

def forward_hook(module, input, output):
    activations.append(output.detach().cpu())

h_f = final_conv_layer.register_forward_hook(forward_hook)
h_b = final_conv_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Forward & Backward
# ======================
resnet50.eval()
output = resnet50(input_tensor)
pred_class = output.argmax(dim=1).item()

# Zero old grads
resnet50.zero_grad()

# Backward wrt predicted class
one_hot = torch.zeros_like(output)
one_hot[0][pred_class] = 1
output.backward(gradient=one_hot.to(device))

# ======================
# 🔹 Compute Grad-CAM
# ======================
if gradients and activations:
    grads = gradients[0].numpy()[0]     # (C,H,W)
    acts  = activations[0].numpy()[0]   # (C,H,W)

    weights = np.mean(grads, axis=(1, 2))
    cam = np.zeros(acts.shape[1:], dtype=np.float32)

    for i, w in enumerate(weights):
        cam += w * acts[i]

    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-8)
    cam = cv2.resize(cam, (img_rgb.shape[1], img_rgb.shape[0]))

    # Overlay heatmap
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_rgb, 0.5, heatmap, 0.5, 0)

    # ======================
    # 🔹 Show Results
    # ======================
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(img_rgb)
    plt.title(f"Original\nPred: {class_names[pred_class]}")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(overlay)
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")
    plt.show()
else:
    print("⚠️ Hooks failed – gradients/activations empty!")

# Cleanup
h_f.remove()
h_b.remove()

"""Batch Grad-CAM Visualization"""

import os
import matplotlib.pyplot as plt
import cv2
import numpy as np

# ======================
# 🔹 Hook registration
# ======================
activations, gradients = {}, {}

def forward_hook(module, input, output):
    activations["value"] = output

def backward_hook(module, grad_input, grad_output):
    gradients["value"] = grad_output[0]

target_layer = resnet50.layer4[-1].conv2  # last conv layer of ResNet50
fwd_hook = target_layer.register_forward_hook(forward_hook)
bwd_hook = target_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Grad-CAM on Misclassified Samples
# ======================
resnet50.eval()
os.makedirs("/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/gradcam_misclassified", exist_ok=True)

N = 6   # number of misclassified samples to visualize
plt.figure(figsize=(14, 8))

for i, (img, true_label, pred_label, confidence) in enumerate(misclassified[:N]):
    input_tensor = img.unsqueeze(0).to(device)  # misclassified already has tensors
    resnet50.zero_grad()

    # Forward + backward
    output = resnet50(input_tensor)
    output[0, pred_label].backward()  # backprop wrt predicted (wrong) class

    # ======================
    # 🔹 Grad-CAM Calculation
    # ======================
    grads = gradients["value"]
    acts = activations["value"]

    weights = grads.mean(dim=[2, 3], keepdim=True)
    cam = (weights * acts).sum(dim=1).squeeze().cpu().detach().numpy()
    cam = np.maximum(cam, 0)
    cam = cv2.resize(cam, (224, 224))
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    # ======================
    # 🔹 Overlay Heatmap
    # ======================
    img_np = img.permute(1, 2, 0).numpy()
    img_np = ((img_np * 0.5) + 0.5) * 255
    img_np = np.clip(img_np, 0, 255).astype(np.uint8)

    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_np, 0.5, heatmap, 0.5, 0)
    overlay = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)

    # ======================
    # 🔹 Save Result
    # ======================
    true_name = class_names[true_label]
    pred_name = class_names[pred_label]
    save_path = f"gradcam_misclassified/misclassified_{i+1}_T-{true_name}_P-{pred_name}.png"
    cv2.imwrite(save_path, cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

    # ======================
    # 🔹 Plot
    # ======================
    plt.subplot(2, 3, i+1)
    plt.imshow(overlay)
    plt.title(f"T: {true_name}\nP: {pred_name}\nConf: {confidence:.2f}")
    plt.axis("off")

plt.suptitle("Grad-CAM on Misclassified Samples", fontsize=16)
plt.tight_layout()
plt.show()

# Remove hooks
fwd_hook.remove()
bwd_hook.remove()

"""# EfficientNet

1. Install & Import
"""

!pip install efficientnet_pytorch

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms, datasets
from torch.utils.data import DataLoader
from efficientnet_pytorch import EfficientNet
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

"""Training Loop with Early Stopping"""

import timm
import torch
import torch.optim as optim
from tqdm import tqdm
import copy
import os

# ===========================
# Model, Optimizer & Scheduler
# ===========================
efficientnet_b0 = timm.create_model('efficientnet_b0', pretrained=True, num_classes=num_classes)
efficientnet_b0 = efficientnet_b0.to(device)

optimizer_b0 = optim.Adam(efficientnet_b0.parameters(), lr=LEARNING_RATE)
scheduler_b0 = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_b0, mode='max', patience=2, factor=0.3
)
print("✅ EfficientNet-B0 ready")

# ===========================
# Training Config
# ===========================
save_path_b0 = os.path.join(BASE_PATH, "models", "best_efficientnetb0.pth")
TOTAL_EPOCHS_B0 = 20
start_epoch_b0 = 0
best_val_acc_b0 = 0
early_stop_counter_b0 = 0

# ===========================
# Resume from checkpoint if exists
# ===========================
if os.path.exists(save_path_b0):
    print(f"🔄 Loading checkpoint from {save_path_b0}")
    checkpoint = torch.load(save_path_b0)
    efficientnet_b0.load_state_dict(checkpoint['model_state_dict'])
    optimizer_b0.load_state_dict(checkpoint['optimizer_state_dict'])
    start_epoch_b0 = checkpoint['epoch'] + 1
    best_val_acc_b0 = checkpoint['best_val_acc']
    print(f"✅ Resuming from epoch {start_epoch_b0}, best_val_acc={best_val_acc_b0:.4f}")

# ===========================
# Training Loop
# ===========================
for epoch in range(start_epoch_b0, TOTAL_EPOCHS_B0):
    # ---- Training ----
    efficientnet_b0.train()
    running_loss, correct, total = 0.0, 0, 0

    loop = tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Epoch {epoch+1}/{TOTAL_EPOCHS_B0}")
    for _, (images, labels) in loop:
        images, labels = images.to(device), labels.to(device)

        optimizer_b0.zero_grad()
        outputs = efficientnet_b0(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_b0.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        loop.set_postfix(train_loss=running_loss/total, train_acc=correct/total)

    train_loss = running_loss / total
    train_acc = correct / total

    # ---- Validation ----
    efficientnet_b0.eval()
    val_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = efficientnet_b0(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    val_loss /= total
    val_acc = correct / total

    scheduler_b0.step(val_acc)

    print(f"Epoch {epoch+1}/{TOTAL_EPOCHS_B0} "
          f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
          f"Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")

    # ---- Early Stopping & Checkpoint ----
    if val_acc > best_val_acc_b0:
        best_val_acc_b0 = val_acc
        best_model_wts_b0 = copy.deepcopy(efficientnet_b0.state_dict())
        torch.save({
            'epoch': epoch,
            'model_state_dict': efficientnet_b0.state_dict(),
            'optimizer_state_dict': optimizer_b0.state_dict(),
            'best_val_acc': best_val_acc_b0
        }, save_path_b0)
        print(f"📌 Best model saved: {save_path_b0}")
        early_stop_counter_b0 = 0
    else:
        early_stop_counter_b0 += 1
        if early_stop_counter_b0 >= PATIENCE:
            print("⏹️ Early stopping triggered.")
            break

# Load best model at the end
efficientnet_b0.load_state_dict(torch.load(save_path_b0)['model_state_dict'])
print(f"✅ Training complete. Best Val Acc = {best_val_acc_b0:.4f}")

""" Evaluation on Test Set"""

# ================================
# 📌 Evaluation on Validation/Test Set
# ================================
import torch
from sklearn.metrics import classification_report

# Load best EfficientNet-B0
model = efficientnet_b0
# Load the entire checkpoint dictionary first
checkpoint = torch.load("/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/models/best_efficientnetb0.pth")
# Then load the model state dict from the checkpoint
model.load_state_dict(checkpoint['model_state_dict'])
model = model.to(device)
model.eval()

all_preds, all_labels = [], []

with torch.no_grad():
    for imgs, labels in val_loader:
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs)
        _, preds = outputs.max(1)
        all_preds.extend(preds.cpu().tolist())
        all_labels.extend(labels.cpu().tolist())

# Classification report
print("📊 Classification Report for EfficientNet-B0:")
print(classification_report(all_labels, all_preds, target_names=class_names))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np

# Confusion matrix
cm = confusion_matrix(all_labels, all_preds)

# Normalize for better visualization (optional)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(18, 15))
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap="Blues",
            xticklabels=class_names, yticklabels=class_names,
            annot_kws={"size": 10})
plt.xlabel('Predicted Class', fontsize=14)
plt.ylabel('True Class', fontsize=14)
plt.title('Normalized Confusion Matrix - EfficientNet-B0', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Misclassified Examples Visualization (EfficientNet-B0)"""

# ================================
# 📌 Misclassified Examples Visualization (EfficientNet-B0)
# ================================
import matplotlib.pyplot as plt
import torch.nn.functional as F

efficientnet_b0.eval()
misclassified = []

# Collect misclassified examples
with torch.no_grad():
    for images, labels in val_loader:  # use val_loader or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b0(images)
        probs = F.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        for i in range(len(labels)):
            if preds[i] != labels[i]:
                misclassified.append((
                    images[i].cpu(),
                    labels[i].item(),
                    preds[i].item(),
                    probs[i][preds[i]].item()
                ))

# Sort by model confidence in wrong prediction
misclassified = sorted(misclassified, key=lambda x: x[3], reverse=True)

# Dataset class names
class_names = train_dataset.classes

# ================================
# Plot Top Misclassified Examples
# ================================
plt.figure(figsize=(15, 10))
for idx, (img, true_label, pred_label, confidence) in enumerate(misclassified[:12]):
    plt.subplot(3, 4, idx + 1)

    # Denormalize (ImageNet mean/std)
    img = img.permute(1, 2, 0).numpy()
    img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
    img = img.clip(0, 1)

    plt.imshow(img)
    plt.title(
        f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.2f})",
        fontsize=9
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# Optional: Save figure
plt.savefig("/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/figures/misclassified_efficientnetb0.png")

"""Visualize Class-wise Performance with Per-Class ROC"""

# ================================
# 📌 Per-Class ROC Curves (EfficientNet-B0)
# ================================
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np
import torch

efficientnet_b0.eval()
y_true = []
y_probs = []

with torch.no_grad():
    for images, labels in val_loader:  # use val_loader or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b0(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())

# Stack predictions & convert labels
y_probs = np.vstack(y_probs)  # shape: (num_samples, num_classes)
y_true = np.array(y_true)

# Binarize labels for one-vs-rest ROC
y_true_bin = label_binarize(y_true, classes=list(range(len(class_names))))
n_classes = y_true_bin.shape[1]

# Compute ROC curve and AUC for each class
fpr, tpr, roc_auc = {}, {}, {}
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot all ROC curves
plt.figure(figsize=(16, 12))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], lw=2,
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([-0.01, 1.01])
plt.ylim([-0.01, 1.01])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('Per-Class ROC Curves - EfficientNet-B0', fontsize=14)
plt.legend(loc="lower right", fontsize='small')
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

"""Per-Class Precision-Recall Curves"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from sklearn.metrics import precision_recall_curve, average_precision_score
import torch

# ======================
# 🔹 Get True Labels & Predicted Probabilities for EfficientNet-B0
# ======================
efficientnet_b0.eval()
y_true = []
y_probs = []

with torch.no_grad():
    for images, labels in val_loader:  # Use your validation loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b0(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())

# Stack predictions and convert to numpy
y_probs = np.vstack(y_probs)
y_true = np.array(y_true)

# ======================
# 🔹 Convert to one-hot for PR computation
# ======================
num_classes = len(class_names)
y_true_binarized = label_binarize(y_true, classes=list(range(num_classes)))

# ======================
# 🔹 Plot Precision-Recall per class
# ======================
plt.figure(figsize=(12, 10))
colors = plt.cm.get_cmap("tab10", num_classes)

for i in range(num_classes):
    precision, recall, _ = precision_recall_curve(y_true_binarized[:, i], y_probs[:, i])
    ap_score = average_precision_score(y_true_binarized[:, i], y_probs[:, i])

    plt.plot(recall, precision, lw=2, color=colors(i),
             label=f"{class_names[i]} (AP = {ap_score:.2f})")

# ======================
# 🔹 Micro-average Precision-Recall
# ======================
precision_micro, recall_micro, _ = precision_recall_curve(y_true_binarized.ravel(),
                                                         y_probs.ravel())
ap_micro = average_precision_score(y_true_binarized, y_probs, average="micro")
plt.plot(recall_micro, precision_micro, linestyle='--', color='black',
         label=f"Micro-average (AP = {ap_micro:.2f})")

# ======================
# 🔹 Final Formatting
# ======================
plt.xlabel("Recall", fontsize=12)
plt.ylabel("Precision", fontsize=12)
plt.title("EfficientNet-B0: Per-Class Precision-Recall Curves", fontsize=14)
plt.legend(loc="best", fontsize="small")
plt.grid(True, linestyle="--", alpha=0.7)
plt.tight_layout()
plt.show()

"""Grad-Cam with PyTorch"""

import torch
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image

# ======================
# 🔹 Preprocessing (must match training transforms)
# ======================
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),   # same as training
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],  # ImageNet normalization
                         std=[0.229, 0.224, 0.225])
])

# ======================
# 🔹 Select image
# ======================
# From misclassified list or any image
img_tensor, true_label, pred_label, conf = misclassified[0]
# Denormalize using the correct mean and std
img_np = img_tensor.permute(1, 2, 0).numpy()
img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
img_np = np.clip(img_np, 0, 1)
img_rgb = (img_np * 255).astype(np.uint8)

input_tensor = img_tensor.unsqueeze(0).to(device)  # add batch dimension

# ======================
# 🔹 Hook setup for EfficientNet-B0
# ======================
# Last convolutional layer for timm EfficientNet-B0
final_conv_layer = efficientnet_b0.conv_head  # Access the conv_head layer
gradients, activations = [], []

def backward_hook(module, grad_in, grad_out):
    gradients.append(grad_out[0].detach().cpu())

def forward_hook(module, input, output):
    activations.append(output.detach().cpu())

h_f = final_conv_layer.register_forward_hook(forward_hook)
h_b = final_conv_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Forward & Backward
# ======================
efficientnet_b0.eval()
output = efficientnet_b0(input_tensor)
pred_class = output.argmax(dim=1).item()

# Zero old grads
efficientnet_b0.zero_grad()

# Backward wrt predicted class
one_hot = torch.zeros_like(output)
one_hot[0][pred_class] = 1
output.backward(gradient=one_hot.to(device))

# ======================
# 🔹 Compute Grad-CAM
# ======================
if gradients and activations:
    grads = gradients[0].numpy()[0]     # (C,H,W)
    acts  = activations[0].numpy()[0]   # (C,H,W)

    weights = np.mean(grads, axis=(1, 2))
    cam = np.zeros(acts.shape[1:], dtype=np.float32)

    for i, w in enumerate(weights):
        cam += w * acts[i]

    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-8)
    cam = cv2.resize(cam, (img_rgb.shape[1], img_rgb.shape[0]))

    # Overlay heatmap
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    # Ensure overlay image is in the correct format (RGB)
    overlay = cv2.addWeighted(cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR), 0.5, heatmap, 0.5, 0)
    overlay = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)


    # ======================
    # 🔹 Show Results
    # ======================
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(img_rgb)
    plt.title(f"Original\nPred: {class_names[pred_class]}")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(overlay)
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")
    plt.show()
else:
    print("⚠️ Hooks failed – gradients/activations empty!")

# Cleanup hooks
h_f.remove()
h_b.remove()

"""Batch Grad-CAM Visualization"""

import os
import matplotlib.pyplot as plt
import cv2
import numpy as np
import torch

# ======================
# 🔹 Hook registration
# ======================
activations, gradients = {}, {}

def forward_hook(module, input, output):
    activations["value"] = output

def backward_hook(module, grad_input, grad_output):
    gradients["value"] = grad_output[0]

# Last convolutional block of EfficientNet-B0
target_layer = efficientnet_b0.conv_head  # Access the conv_head layer
fwd_hook = target_layer.register_forward_hook(forward_hook)
bwd_hook = target_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Grad-CAM on Misclassified Samples
# ======================
efficientnet_b0.eval()
os.makedirs("/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/gradcam_misclassified_b0", exist_ok=True)

N = 6   # number of misclassified samples to visualize
plt.figure(figsize=(14, 8))

for i, (img, true_label, pred_label, confidence) in enumerate(misclassified[:N]):
    input_tensor = img.unsqueeze(0).to(device)  # misclassified already has tensors
    efficientnet_b0.zero_grad()

    # Forward + backward
    output = efficientnet_b0(input_tensor)
    output[0, pred_label].backward()  # backprop wrt predicted (wrong) class

    # ======================
    # 🔹 Grad-CAM Calculation
    # ======================
    grads = gradients["value"]
    acts = activations["value"]

    weights = grads.mean(dim=[2, 3], keepdim=True)
    cam = (weights * acts).sum(dim=1).squeeze().cpu().detach().numpy()
    cam = np.maximum(cam, 0)
    cam = cv2.resize(cam, (224, 224))
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    # ======================
    # 🔹 Overlay Heatmap
    # ======================
    img_np = img.permute(1, 2, 0).numpy()
    img_np = ((img_np * 0.229) + 0.485) * 255  # denormalize approx
    img_np = np.clip(img_np, 0, 255).astype(np.uint8)

    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_np, 0.5, heatmap, 0.5, 0)
    overlay = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)

    # ======================
    # 🔹 Save Result
    # ======================
    true_name = class_names[true_label]
    pred_name = class_names[pred_label]
    save_path = f"gradcam_misclassified_b0/misclassified_{i+1}_T-{true_name}_P-{pred_name}.png"
    cv2.imwrite(save_path, cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

    # ======================
    # 🔹 Plot
    # ======================
    plt.subplot(2, 3, i+1)
    plt.imshow(overlay)
    plt.title(f"T: {true_name}\nP: {pred_name}\nConf: {confidence:.2f}")
    plt.axis("off")

plt.suptitle("Grad-CAM on Misclassified Samples (EfficientNet-B0)", fontsize=16)
plt.tight_layout()
plt.show()

# Remove hooks
fwd_hook.remove()
bwd_hook.remove()

"""# EfficientNet-b3"""

# ================================
# 📌 EfficientNet-B3 Training
# ================================

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import os

# -------------------------
# Model, device, criterion
# -------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

efficientnet_b3 = timm.create_model('efficientnet_b3', pretrained=True, num_classes=num_classes)
efficientnet_b3 = efficientnet_b3.to(device)

optimizer_b3 = optim.Adam(efficientnet_b3.parameters(), lr=1e-3)
scheduler_b3 = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_b3, mode='max', patience=2, factor=0.3
)

criterion = nn.CrossEntropyLoss(weight=class_weights)

# -------------------------
# Hyperparameters
# -------------------------
EPOCHS = 25  # change from 20 to 25
best_val_acc = 0.0
early_stop_counter = 0
PATIENCE = 5

# -------------------------
# Training Loop
# -------------------------
for epoch in range(EPOCHS):
    efficientnet_b3.train()
    train_loss, correct, total = 0.0, 0, 0

    loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", ncols=100)
    for images, labels in loop:
        images, labels = images.to(device), labels.to(device)

        optimizer_b3.zero_grad()
        outputs = efficientnet_b3(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_b3.step()

        train_loss += loss.item() * images.size(0)
        _, preds = outputs.max(1)
        correct += preds.eq(labels).sum().item()
        total += labels.size(0)

        loop.set_postfix(train_acc=correct/total, train_loss=train_loss/total)

    train_loss /= total
    train_acc = correct / total

    # -------------------------
    # Validation
    # -------------------------
    efficientnet_b3.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = efficientnet_b3(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * images.size(0)
            _, preds = outputs.max(1)
            val_correct += preds.eq(labels).sum().item()
            val_total += labels.size(0)

    val_loss /= val_total
    val_acc = val_correct / val_total

    print(f"Epoch {epoch+1}/{EPOCHS} Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")

    # -------------------------
    # Save Best Model
    # -------------------------
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(efficientnet_b3.state_dict(), os.path.join(BASE_PATH, "models", "best_efficientnetb3.pth"))
        print(f"📌 Best model saved: {os.path.join(BASE_PATH, 'models', 'best_efficientnetb3.pth')}")
        early_stop_counter = 0
    else:
        early_stop_counter += 1

    # Scheduler step
    scheduler_b3.step(val_acc)

    # Early stopping
    if early_stop_counter >= PATIENCE:
        print("⏹️ Early stopping triggered.")
        break

print(f"✅ Training complete. Best Val Acc = {best_val_acc:.4f}")

"""Evaluate on Test Set"""

from sklearn.metrics import classification_report, confusion_matrix
import torch

# Load best saved model
efficientnet_b3.load_state_dict(torch.load(os.path.join(BASE_PATH, "models", "best_efficientnetb3.pth")))
efficientnet_b3.eval()

all_preds, all_labels = [], []

with torch.no_grad():
    for images, labels in val_loader:  # use val_loader or test_loader as per your setup
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b3(images)
        _, preds = outputs.max(1)
        all_preds.extend(preds.cpu().tolist())
        all_labels.extend(labels.cpu().tolist())

# ======================
# Classification Report
# ======================
print("📊 Classification Report for EfficientNet-B3:")
print(classification_report(all_labels, all_preds, target_names=class_names))

"""Confusion Matrix"""

# ======================
# Confusion Matrix
# ======================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(18, 15))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names,
            annot_kws={"size": 10})
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix - EfficientNet-B3')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Misclassified Examples Visualization"""

import matplotlib.pyplot as plt
import torch.nn.functional as F

efficientnet_b3.eval()
misclassified = []

# Collect misclassified examples
with torch.no_grad():
    for images, labels in val_loader:  # use val_loader or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b3(images)
        probs = F.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        for i in range(len(labels)):
            if preds[i] != labels[i]:
                misclassified.append((
                    images[i].cpu(),
                    labels[i].item(),
                    preds[i].item(),
                    probs[i][preds[i]].item()
                ))

# Sort by confidence in wrong prediction
misclassified = sorted(misclassified, key=lambda x: x[3], reverse=True)

# Use dataset class names
class_names = train_dataset.classes

# ======================
# Plot Top Misclassified Examples
# ======================
plt.figure(figsize=(15, 10))
for idx, (img, true_label, pred_label, confidence) in enumerate(misclassified[:12]):
    plt.subplot(3, 4, idx + 1)

    # Denormalize (ImageNet mean/std)
    img = img.permute(1, 2, 0).numpy()
    img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]  # unnormalize
    img = img.clip(0, 1)

    plt.imshow(img)
    plt.title(
        f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.2f})",
        fontsize=9
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# Optional: Save figure
plt.savefig(os.path.join(BASE_PATH, "figures", "misclassified_efficientnetb3.png"))

"""Misclassified Examples – Sorted by Lowest Confidence"""

import matplotlib.pyplot as plt
import torch.nn.functional as F

efficientnet_b3.eval()
misclassified = []

# Collect misclassified examples
with torch.no_grad():
    for images, labels in val_loader:  # use val_loader or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b3(images)
        probs = F.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        for i in range(len(labels)):
            if preds[i] != labels[i]:
                misclassified.append((
                    images[i].cpu(),
                    labels[i].item(),
                    preds[i].item(),
                    probs[i][preds[i]].item()  # model confidence
                ))

# Sort by **lowest confidence** in wrong predictions
misclassified = sorted(misclassified, key=lambda x: x[3])  # ascending

# Use dataset class names
class_names = train_dataset.classes

# ======================
# Plot Top Misclassified Examples (Lowest Confidence)
# ======================
plt.figure(figsize=(15, 10))
for idx, (img, true_label, pred_label, confidence) in enumerate(misclassified[:12]):
    plt.subplot(3, 4, idx + 1)

    # Denormalize (ImageNet mean/std)
    img = img.permute(1, 2, 0).numpy()
    img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]  # unnormalize
    img = img.clip(0, 1)

    plt.imshow(img)
    plt.title(
        f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.2f})",
        fontsize=9
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# Optional: Save figure
plt.savefig(os.path.join(BASE_PATH, "figures", "misclassified_lowconf_efficientnetb3.png"))

"""Visualize Class-wise Performance with Per-Class ROC"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np
import torch

efficientnet_b3.eval()
y_true = []
y_probs = []

# Collect predictions & probabilities
with torch.no_grad():
    for images, labels in val_loader:  # or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b3(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())

# Stack predictions & convert labels
y_probs = np.vstack(y_probs)  # shape: (num_samples, num_classes)
y_true = np.array(y_true)

# Binarize labels for one-vs-rest ROC
y_true_bin = label_binarize(y_true, classes=list(range(len(class_names))))
n_classes = y_true_bin.shape[1]

# Compute ROC curve and AUC for each class
fpr, tpr, roc_auc = {}, {}, {}
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot all ROC curves
plt.figure(figsize=(16, 12))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], lw=2,
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)  # diagonal
plt.xlim([-0.01, 1.01])
plt.ylim([-0.01, 1.01])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('Per-Class ROC Curves (EfficientNet-B3)', fontsize=14)
plt.legend(loc="lower right", fontsize='small')
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

"""Per-Class Precision-Recall Curves"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from sklearn.metrics import precision_recall_curve, average_precision_score

# ======================
# 🔹 True Labels & Predicted Probabilities
# ======================
# EfficientNet-B3 model must have been evaluated on val_loader or test_loader
efficientnet_b3.eval()
y_true = []
y_probs = []

with torch.no_grad():
    for images, labels in val_loader:  # or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = efficientnet_b3(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())

# Stack predictions & convert labels
y_probs = np.vstack(y_probs)  # shape: (num_samples, num_classes)
y_true = np.array(y_true)

# Binarize labels for one-vs-rest PR curves
num_classes = len(class_names)
y_true_binarized = label_binarize(y_true, classes=list(range(num_classes)))

# ======================
# 🔹 Plot Precision-Recall per class
# ======================
plt.figure(figsize=(12, 10))
colors = plt.cm.get_cmap("tab10", num_classes)

for i in range(num_classes):
    precision, recall, _ = precision_recall_curve(y_true_binarized[:, i], y_probs[:, i])
    ap_score = average_precision_score(y_true_binarized[:, i], y_probs[:, i])

    plt.plot(recall, precision, lw=2, color=colors(i),
             label=f"{class_names[i]} (AP = {ap_score:.2f})")

# ======================
# 🔹 Micro-average Precision-Recall
# ======================
precision_micro, recall_micro, _ = precision_recall_curve(y_true_binarized.ravel(),
                                                         y_probs.ravel())
ap_micro = average_precision_score(y_true_binarized, y_probs, average="micro")
plt.plot(recall_micro, precision_micro, linestyle='--', color='black',
         label=f"Micro-average (AP = {ap_micro:.2f})")

# ======================
# 🔹 Final Formatting
# ======================
plt.xlabel("Recall", fontsize=12)
plt.ylabel("Precision", fontsize=12)
plt.title("Per-Class Precision-Recall Curves (EfficientNet-B3)", fontsize=14)
plt.legend(loc="best", fontsize="small")
plt.grid(True, linestyle="--", alpha=0.7)
plt.tight_layout()
plt.show()

"""Grad‑CAM with PyTorch"""

import torch
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import cv2

# ======================
# 🔹 Preprocessing (must match training transforms)
# ======================
preprocess = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),  # IMAGE_SIZE = 224
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],  # ImageNet normalization
                         std=[0.229, 0.224, 0.225])
])

# ======================
# 🔹 Select image from misclassified list or manually
# ======================
# Example: pick first misclassified
img_tensor, true_label, pred_label, conf = misclassified[0]  # list for EfficientNet-B3
img_np = img_tensor.permute(1, 2, 0).numpy()
img_np = np.clip(img_np * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406], 0, 1)  # denormalize
img_np = (img_np * 255).astype(np.uint8)
img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)

input_tensor = img_tensor.unsqueeze(0).to(device)

# ======================
# 🔹 Hook setup
# ======================
# For EfficientNet-B3, the last conv layer is `conv_head`
final_conv_layer = efficientnet_b3.conv_head
gradients, activations = [], []

def backward_hook(module, grad_in, grad_out):
    gradients.append(grad_out[0].detach().cpu())

def forward_hook(module, input, output):
    activations.append(output.detach().cpu())

h_f = final_conv_layer.register_forward_hook(forward_hook)
h_b = final_conv_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Forward & Backward
# ======================
efficientnet_b3.eval()
output = efficientnet_b3(input_tensor)
pred_class = output.argmax(dim=1).item()

# Zero old grads
efficientnet_b3.zero_grad()

# Backward wrt predicted class
one_hot = torch.zeros_like(output)
one_hot[0][pred_class] = 1
output.backward(gradient=one_hot.to(device))

# ======================
# 🔹 Compute Grad-CAM
# ======================
if gradients and activations:
    grads = gradients[0].numpy()[0]  # (C,H,W)
    acts = activations[0].numpy()[0] # (C,H,W)

    weights = np.mean(grads, axis=(1, 2))
    cam = np.zeros(acts.shape[1:], dtype=np.float32)

    for i, w in enumerate(weights):
        cam += w * acts[i]

    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-8)
    cam = cv2.resize(cam, (img_rgb.shape[1], img_rgb.shape[0]))

    # Overlay heatmap
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_rgb, 0.5, heatmap, 0.5, 0)

    # ======================
    # 🔹 Show Results
    # ======================
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(img_rgb)
    plt.title(f"Original\nPred: {class_names[pred_class]}")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(overlay)
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")
    plt.show()
else:
    print("⚠️ Hooks failed – gradients/activations empty!")

# Cleanup
h_f.remove()
h_b.remove()

"""Batch Grad-CAM Visualization"""

import os
import matplotlib.pyplot as plt
import cv2
import numpy as np
import torch

# ======================
# 🔹 Hook registration
# ======================
activations, gradients = {}, {}

def forward_hook(module, input, output):
    activations["value"] = output

def backward_hook(module, grad_input, grad_output):
    gradients["value"] = grad_output[0]

# Last convolutional block of EfficientNet-B3
target_layer = efficientnet_b3.conv_head  # Access the conv_head layer for EfficientNet-B3
fwd_hook = target_layer.register_forward_hook(forward_hook)
bwd_hook = target_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Grad-CAM on Misclassified Samples
# ======================
efficientnet_b3.eval() # Use efficientnet_b3 here
# Define save_dir before the loop
save_dir = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/gradcam_misclassified_b3" # Save to a different directory
os.makedirs(save_dir, exist_ok=True)

N = 6   # number of misclassified samples to visualize
plt.figure(figsize=(14, 8))

for i, (img, true_label, pred_label, confidence) in enumerate(misclassified[:N]):
    input_tensor = img.unsqueeze(0).to(device)  # misclassified already has tensors
    efficientnet_b3.zero_grad() # Use efficientnet_b3 here

    # Forward + backward
    output = efficientnet_b3(input_tensor) # Use efficientnet_b3 here
    output[0, pred_label].backward()  # backprop wrt predicted (wrong) class

    # ======================
    # 🔹 Grad-CAM Calculation
    # ======================
    grads = gradients["value"]
    acts = activations["value"]

    weights = grads.mean(dim=[2, 3], keepdim=True)
    cam = (weights * acts).sum(dim=1).squeeze().cpu().detach().numpy()
    cam = np.maximum(cam, 0)
    cam = cv2.resize(cam, (224, 224))
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    # ======================
    # 🔹 Overlay Heatmap
    # ======================
    img_np = img.permute(1, 2, 0).numpy()
    img_np = ((img_np * 0.229) + 0.485) * 255  # denormalize approx
    img_np = np.clip(img_np, 0, 255).astype(np.uint8)

    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_np, 0.5, heatmap, 0.5, 0)
    overlay = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)

    # ======================
    # 🔹 Save Result
    # ======================
    true_name = class_names[true_label]
    pred_name = class_names[pred_label]
    save_path = os.path.join(save_dir, f"misclassified_{i+1}_T-{true_name}_P-{pred_name}.png")
    cv2.imwrite(save_path, cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

    # ======================
    # 🔹 Plot
    # ======================
    plt.subplot(2, 3, i+1)
    plt.imshow(overlay)
    plt.title(f"T: {true_name}\nP: {pred_name}\nConf: {confidence:.2f}")
    plt.axis("off")

plt.suptitle("Grad-CAM on Misclassified Samples (EfficientNet-B3)", fontsize=16) # Update title
plt.tight_layout()
plt.show()

# Remove hooks
fwd_hook.remove()
bwd_hook.remove()

"""# DENSENET 121

Install & Import Libraries
"""

# ================================
# 🔹 Step 1: Install & Import Libraries
# ================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms, datasets
from torch.utils.data import DataLoader
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, precision_recall_curve, average_precision_score
from sklearn.preprocessing import label_binarize
import cv2
from PIL import Image
import os

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

"""TRAINING"""

import timm
import torch
import torch.optim as optim
from tqdm import tqdm
import copy
import os

# ===========================
# Model, Optimizer & Scheduler
# ===========================
densenet121 = timm.create_model('densenet121', pretrained=True, num_classes=num_classes)
densenet121 = densenet121.to(device)

optimizer_dn121 = optim.Adam(densenet121.parameters(), lr=LEARNING_RATE)
scheduler_dn121 = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_dn121, mode='max', patience=2, factor=0.3
)
print("✅ DenseNet-121 ready")

# ===========================
# Training Config
# ===========================
save_path_dn121 = os.path.join(BASE_PATH, "models", "best_dense_net121.pth")
TOTAL_EPOCHS_DN121 = 20
start_epoch_dn121 = 0
best_val_acc_dn121 = 0
early_stop_counter_dn121 = 0

# ===========================
# Resume from checkpoint if exists
# ===========================
if os.path.exists(save_path_dn121):
    print(f"🔄 Loading checkpoint from {save_path_dn121}")
    checkpoint = torch.load(save_path_dn121, map_location=torch.device('cpu'))
    if isinstance(checkpoint, dict) and 'model_state_dict' in checkpoint:
        densenet121.load_state_dict(checkpoint['model_state_dict'])
        # Attempt to load other components if they exist
        if 'optimizer_state_dict' in checkpoint:
            optimizer_dn121.load_state_dict(checkpoint['optimizer_state_dict'])
        if 'epoch' in checkpoint:
            start_epoch_dn121 = checkpoint['epoch'] + 1
        if 'best_val_acc' in checkpoint:
            best_val_acc_dn121 = checkpoint['best_val_acc']
        print(f"✅ Resuming from epoch {start_epoch_dn121}, best_val_acc={best_val_acc_dn121:.4f}")
    else:
        # Assume the checkpoint is just the state_dict
        densenet121.load_state_dict(checkpoint)
        print("✅ Loaded model state dict directly from checkpoint.")


# ===========================
# Training Loop
# ===========================
for epoch in range(start_epoch_dn121, TOTAL_EPOCHS_DN121):
    # ---- Training ----
    densenet121.train()
    running_loss, correct, total = 0.0, 0, 0

    loop = tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Epoch {epoch+1}/{TOTAL_EPOCHS_DN121}")
    for _, (images, labels) in loop:
        images, labels = images.to(device), labels.to(device)

        optimizer_dn121.zero_grad()
        outputs = densenet121(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_dn121.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        loop.set_postfix(train_loss=running_loss/total, train_acc=correct/total)

    train_loss = running_loss / total
    train_acc = correct / total

    # ---- Validation ----
    densenet121.eval()
    val_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = densenet121(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    val_loss /= total
    val_acc = correct / total

    scheduler_dn121.step(val_acc)

    print(f"Epoch {epoch+1}/{TOTAL_EPOCHS_DN121} "
          f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
          f"Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")

    # ---- Early Stopping & Checkpoint ----
    if val_acc > best_val_acc_dn121:
        best_val_acc_dn121 = val_acc
        best_model_wts_dn121 = copy.deepcopy(densenet121.state_dict())
        torch.save({
            'epoch': epoch,
            'model_state_dict': densenet121.state_dict(),
            'optimizer_state_dict': optimizer_dn121.state_dict(),
            'best_val_acc': best_val_acc_dn121
        }, save_path_dn121)
        print(f"📌 Best model saved: {save_path_dn121}")
        early_stop_counter_dn121 = 0
    else:
        early_stop_counter_dn121 += 1
        if early_stop_counter_dn121 >= PATIENCE:
            print("⏹️ Early stopping triggered.")
            break

# Load best model at the end
densenet121.load_state_dict(torch.load(save_path_dn121, map_location=torch.device('cpu'))['model_state_dict'])
print(f"✅ Training complete. Best Val Acc = {best_val_acc_dn121:.4f}")

import timm
import torch
import torch.optim as optim
from tqdm import tqdm
import copy
import os

# ===========================
# Model, Optimizer & Scheduler
# ===========================
densenet121 = timm.create_model('densenet121', pretrained=True, num_classes=num_classes)
densenet121 = densenet121.to(device)

optimizer_dn121 = optim.Adam(densenet121.parameters(), lr=LEARNING_RATE)
scheduler_dn121 = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_dn121, mode='max', patience=2, factor=0.3
)
print("✅ DenseNet-121 ready")

# ===========================
# Training Config
# ===========================
save_path_dn121 = os.path.join(BASE_PATH, "models", "best_dense_net121.pth")
TOTAL_EPOCHS_DN121 = 20
start_epoch_dn121 = 0
best_val_acc_dn121 = 0
early_stop_counter_dn121 = 0

# ===========================
# Resume from checkpoint if exists
# ===========================
if os.path.exists(save_path_dn121):
    print(f"🔄 Loading checkpoint from {save_path_dn121}")
    checkpoint = torch.load(save_path_dn121, map_location=torch.device('cpu'))
    if isinstance(checkpoint, dict) and 'model_state_dict' in checkpoint:
        densenet121.load_state_dict(checkpoint['model_state_dict'])
        # Attempt to load other components if they exist
        if 'optimizer_state_dict' in checkpoint:
            optimizer_dn121.load_state_dict(checkpoint['optimizer_state_dict'])
        if 'epoch' in checkpoint:
            start_epoch_dn121 = checkpoint['epoch'] + 1
        if 'best_val_acc' in checkpoint:
            best_val_acc_dn121 = checkpoint['best_val_acc']
        print(f"✅ Resuming from epoch {start_epoch_dn121}, best_val_acc={best_val_acc_dn121:.4f}")
    else:
        # Assume the checkpoint is just the state_dict
        densenet121.load_state_dict(checkpoint)
        print("✅ Loaded model state dict directly from checkpoint.")


# ===========================
# Training Loop
# ===========================
for epoch in range(start_epoch_dn121, TOTAL_EPOCHS_DN121):
    # ---- Training ----
    densenet121.train()
    running_loss, correct, total = 0.0, 0, 0

    loop = tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Epoch {epoch+1}/{TOTAL_EPOCHS_DN121}")
    for _, (images, labels) in loop:
        images, labels = images.to(device), labels.to(device)

        optimizer_dn121.zero_grad()
        outputs = densenet121(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_dn121.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        loop.set_postfix(train_loss=running_loss/total, train_acc=correct/total)

    train_loss = running_loss / total
    train_acc = correct / total

    # ---- Validation ----
    densenet121.eval()
    val_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = densenet121(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    val_loss /= total
    val_acc = correct / total

    scheduler_dn121.step(val_acc)

    print(f"Epoch {epoch+1}/{TOTAL_EPOCHS_DN121} "
          f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
          f"Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")

    # ---- Early Stopping & Checkpoint ----
    if val_acc > best_val_acc_dn121:
        best_val_acc_dn121 = val_acc
        best_model_wts_dn121 = copy.deepcopy(densenet121.state_dict())
        torch.save({
            'epoch': epoch,
            'model_state_dict': densenet121.state_dict(),
            'optimizer_state_dict': optimizer_dn121.state_dict(),
            'best_val_acc': best_val_acc_dn121
        }, save_path_dn121)
        print(f"📌 Best model saved: {save_path_dn121}")
        early_stop_counter_dn121 = 0
    else:
        early_stop_counter_dn121 += 1
        if early_stop_counter_dn121 >= PATIENCE:
            print("⏹️ Early stopping triggered.")
            break

# Load best model at the end
densenet121.load_state_dict(torch.load(save_path_dn121, map_location=torch.device('cpu'))['model_state_dict'])
print(f"✅ Training complete. Best Val Acc = {best_val_acc_dn121:.4f}")

"""valuation on Test Set for DenseNet121"""

# ================================
# 🔹 Evaluate DenseNet121 on Test/Validation Set
# ================================

from sklearn.metrics import classification_report, confusion_matrix
import torch

# Load the best saved model
# Load the entire checkpoint dictionary first
checkpoint = torch.load(os.path.join(BASE_PATH, "models", "best_dense_net121.pth"))
# Then load the model state dict from the checkpoint
densenet121.load_state_dict(checkpoint['model_state_dict'])
densenet121.eval()

all_preds, all_labels = [], []

with torch.no_grad():
    for imgs, labels in val_loader:  # or test_loader if you prefer
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = densenet121(imgs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().tolist())
        all_labels.extend(labels.cpu().tolist())

# ======================
# Classification Report
# ======================
print("📊 Classification Report for DenseNet121:")
print(classification_report(all_labels, all_preds, target_names=class_names))

# ======================
# Overall Accuracy
# ======================
accuracy = sum(np.array(all_preds) == np.array(all_labels)) / len(all_labels)
print(f"✅ Test/Validation Accuracy: {accuracy:.4f}")

# ================================
# 📌 Step 11: Confusion Matrix - Densenet-121
# ================================

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Put model in evaluation mode
densenet121.eval()
y_true = []
y_pred = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        outputs = resnet50(images)
        _, predicted = torch.max(outputs, 1)

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(predicted.cpu().numpy())

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(14, 12))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.title("Confusion Matrix on Test Set - Densenet-121")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""misclassified examples visualization"""

import matplotlib.pyplot as plt
import torch.nn.functional as F

densenet121.eval()
misclassified = []

# Collect misclassified examples
with torch.no_grad():
    for images, labels in val_loader:  # use val_loader or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = densenet121(images)
        probs = F.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        for i in range(len(labels)):
            if preds[i] != labels[i]:
                misclassified.append((
                    images[i].cpu(),
                    labels[i].item(),
                    preds[i].item(),
                    probs[i][preds[i]].item()
                ))

# Sort by confidence in wrong prediction
misclassified = sorted(misclassified, key=lambda x: x[3], reverse=True)

# Use dataset class names
class_names = train_dataset.classes

# ======================
# Plot Top Misclassified Examples
# ======================
plt.figure(figsize=(15, 10))
for idx, (img, true_label, pred_label, confidence) in enumerate(misclassified[:12]):
    plt.subplot(3, 4, idx + 1)

    # Denormalize (ImageNet mean/std)
    img = img.permute(1, 2, 0).numpy()
    img = img * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]  # unnormalize
    img = img.clip(0, 1)

    plt.imshow(img)
    plt.title(
        f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.2f})",
        fontsize=9
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# Optional: Save figure
plt.savefig(os.path.join(BASE_PATH, "figures", "misclassified_densenet121.png"))

"""per-class ROC visualization"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np
import torch

densenet121.eval()
y_true = []
y_probs = []

# Collect predictions & probabilities
with torch.no_grad():
    for images, labels in val_loader:  # or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = densenet121(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())

# Stack predictions & convert labels
y_probs = np.vstack(y_probs)  # shape: (num_samples, num_classes)
y_true = np.array(y_true)

# Binarize labels for one-vs-rest ROC
y_true_bin = label_binarize(y_true, classes=list(range(len(class_names))))
n_classes = y_true_bin.shape[1]

# Compute ROC curve and AUC for each class
fpr, tpr, roc_auc = {}, {}, {}
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot all ROC curves
plt.figure(figsize=(16, 12))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], lw=2,
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)  # diagonal
plt.xlim([-0.01, 1.01])
plt.ylim([-0.01, 1.01])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('Per-Class ROC Curves (Densenet121)', fontsize=14)
plt.legend(loc="lower right", fontsize='small')
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

"""per-class Precision-Recall curves"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from sklearn.metrics import precision_recall_curve, average_precision_score

# ======================
# 🔹 True Labels & Predicted Probabilities
# ======================
# Densenet121 model must have been evaluated on val_loader or test_loader
densenet121.eval()
y_true = []
y_probs = []

with torch.no_grad():
    for images, labels in val_loader:  # or test_loader
        images, labels = images.to(device), labels.to(device)
        outputs = densenet121(images)
        probs = torch.softmax(outputs, dim=1)

        y_probs.append(probs.cpu().numpy())
        y_true.extend(labels.cpu().numpy())

# Stack predictions & convert labels
y_probs = np.vstack(y_probs)  # shape: (num_samples, num_classes)
y_true = np.array(y_true)

# Binarize labels for one-vs-rest PR curves
num_classes = len(class_names)
y_true_binarized = label_binarize(y_true, classes=list(range(num_classes)))

# ======================
# 🔹 Plot Precision-Recall per class
# ======================
plt.figure(figsize=(12, 10))
colors = plt.cm.get_cmap("tab10", num_classes)

for i in range(num_classes):
    precision, recall, _ = precision_recall_curve(y_true_binarized[:, i], y_probs[:, i])
    ap_score = average_precision_score(y_true_binarized[:, i], y_probs[:, i])

    plt.plot(recall, precision, lw=2, color=colors(i),
             label=f"{class_names[i]} (AP = {ap_score:.2f})")

# ======================
# 🔹 Micro-average Precision-Recall
# ======================
precision_micro, recall_micro, _ = precision_recall_curve(y_true_binarized.ravel(),
                                                         y_probs.ravel())
ap_micro = average_precision_score(y_true_binarized, y_probs, average="micro")
plt.plot(recall_micro, precision_micro, linestyle='--', color='black',
         label=f"Micro-average (AP = {ap_micro:.2f})")

# ======================
# 🔹 Final Formatting
# ======================
plt.xlabel("Recall", fontsize=12)
plt.ylabel("Precision", fontsize=12)
plt.title("Per-Class Precision-Recall Curves (Densenet121)", fontsize=14)
plt.legend(loc="best", fontsize="small")
plt.grid(True, linestyle="--", alpha=0.7)
plt.tight_layout()
plt.show()

"""Grad-CAM"""

import torch
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import cv2

# ======================
# 🔹 Preprocessing (must match training transforms)
# ======================
preprocess = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),  # IMAGE_SIZE = 224
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],  # ImageNet normalization
                         std=[0.229, 0.224, 0.225])
])

# ======================
# 🔹 Select image from misclassified list or manually
# ======================
# Example: pick first misclassified
# Make sure the misclassified list for densenet121 is available or load the data again
# Assuming misclassified list from previous DenseNet121 evaluation is available
# If not, you might need to re-run the evaluation cell first to populate 'misclassified'
try:
    img_tensor, true_label, pred_label, conf = misclassified[0]  # list for Densenet121
except NameError:
    print("⚠️ 'misclassified' list not found. Please run the misclassified examples visualization cell for DenseNet121 first.")
    # Fallback: Load a sample image if misclassified list is not available
    # This requires knowing a sample image path. Replace with a valid path.
    # img_path = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/test/Rosacea/rosacea-104.jpeg" # Example path
    # img_bgr = cv2.imread(img_path)
    # img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    # img_tensor = preprocess(Image.fromarray(img_rgb))
    # true_label = -1 # Unknown true label for manual image
    # pred_label = -1 # Unknown predicted label for manual image
    # conf = -1 # Unknown confidence for manual image
    # input_tensor = img_tensor.unsqueeze(0).to(device)
    exit() # Exit cell execution if misclassified is not found and no fallback is provided


img_np = img_tensor.permute(1, 2, 0).numpy()
img_np = np.clip(img_np * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406], 0, 1)  # denormalize
img_np = (img_np * 255).astype(np.uint8)
img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)

input_tensor = img_tensor.unsqueeze(0).to(device)

# ======================
# 🔹 Hook setup
# ======================
# For Densenet121 from timm, the last conv layer is typically the last layer in the 'features' sequence
final_conv_layer = densenet121.features[-1]
gradients, activations = [], []

def backward_hook(module, grad_in, grad_out):
    gradients.append(grad_out[0].detach().cpu())

def forward_hook(module, input, output):
    activations.append(output.detach().cpu())

h_f = final_conv_layer.register_forward_hook(forward_hook)
h_b = final_conv_layer.register_backward_hook(backward_hook)

# ======================
# 🔹 Forward & Backward
# ======================
densenet121.eval()
output = densenet121(input_tensor) # Use densenet121 here
pred_class = output.argmax(dim=1).item()

# Zero old grads
densenet121.zero_grad() # Use densenet121 here

# Backward wrt predicted class
one_hot = torch.zeros_like(output)
one_hot[0][pred_class] = 1
output.backward(gradient=one_hot.to(device))

# ======================
# 🔹 Compute Grad-CAM
# ======================
if gradients and activations:
    grads = gradients[0].numpy()[0]  # (C,H,W)
    acts = activations[0].numpy()[0] # (C,H,W)

    weights = np.mean(grads, axis=(1, 2))
    cam = np.zeros(acts.shape[1:], dtype=np.float32)

    for i, w in enumerate(weights):
        cam += w * acts[i]

    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-8)
    cam = cv2.resize(cam, (img_rgb.shape[1], img_rgb.shape[0]))

    # Overlay heatmap
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_rgb, 0.5, heatmap, 0.5, 0)

    # ======================
    # 🔹 Show Results
    # ======================
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(img_rgb)
    plt.title(f"Original\nTrue: {class_names[true_label]}\nPred: {class_names[pred_class]} ({conf:.2f})") # Add true label and confidence
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(overlay)
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")
    plt.show()
else:
    print("⚠️ Hooks failed – gradients/activations empty!")

# Cleanup
h_f.remove()
h_b.remove()

"""Batch Grad-CAM visualization"""

import os
import matplotlib.pyplot as plt
import cv2
import numpy as np
import torch

# ======================
# 🔹 Hook registration
# ======================
activations, gradients = {}, {}

def forward_hook(module, input, output):
    activations["value"] = output

def backward_hook(module, grad_input, grad_output):
    gradients["value"] = grad_output[0]

# Last convolutional block of Densenet121
target_layer = densenet121.features[-1]  # Corrected: Access the last layer in the 'features' sequence
fwd_hook = target_layer.register_forward_hook(forward_hook)
bwd_hook = target_layer.register_backward_hook(backward_hook)

# Ensure output directory exists
save_dir = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease/gradcam_misclassified_densenet"
os.makedirs(save_dir, exist_ok=True)

# Visualize top N misclassified samples
N = 6
plt.figure(figsize=(14, 8))

for i, (img, true_label, pred_label, confidence) in enumerate(misclassified[:N]):
    input_tensor = img.unsqueeze(0).to(device)
    densenet121.zero_grad()

    # Forward + backward
    output = densenet121(input_tensor)
    output[0, pred_label].backward()  # backprop wrt predicted (wrong) class

    # Grad-CAM calculation
    grads = gradients["value"]
    acts = activations["value"]

    weights = grads.mean(dim=[2,3], keepdim=True)
    cam = (weights * acts).sum(dim=1).squeeze().cpu().detach().numpy()
    cam = np.maximum(cam, 0)
    cam = cv2.resize(cam, (224,224))
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    # Overlay heatmap on image
    img_np = img.permute(1,2,0).numpy()
    img_np = img_np * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]  # denormalize
    img_np = np.clip(img_np, 0, 1)
    img_np = (img_np*255).astype(np.uint8)

    heatmap = cv2.applyColorMap(np.uint8(255*cam), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(img_np, 0.5, heatmap, 0.5, 0)
    overlay = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)

    # Save
    true_name = class_names[true_label]
    pred_name = class_names[pred_label]
    save_path = os.path.join(save_dir, f"misclassified_{i+1}_T-{true_name}_P-{pred_name}.png")
    cv2.imwrite(save_path, cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

    # Plot
    plt.subplot(2, 3, i+1)
    plt.imshow(overlay)
    plt.title(f"T: {true_name}\nP: {pred_name}\nConf: {confidence:.2f}")
    plt.axis("off")

plt.suptitle("Grad-CAM on Misclassified DenseNet121 Samples", fontsize=16)
plt.tight_layout()
plt.show()

# Remove hooks
fwd_hook.remove()
bwd_hook.remove()

import torch
import timm
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report, accuracy_score
import pandas as pd
import os

# =======================
# Paths & Config
# =======================
BASE_PATH = "/content/drive/MyDrive/MINOR_PROJECT_25/SkinDisease"
MODEL_PATHS = {
    'resnet50': os.path.join(BASE_PATH, "models/best_resnet50.pth"),
    'efficientnet_b0': os.path.join(BASE_PATH, "models/best_efficientnetb0.pth"),
    'efficientnet_b3': os.path.join(BASE_PATH, "models/best_efficientnetb3.pth"),
    'densenet121': os.path.join(BASE_PATH, "models/best_dense_net121.pth")
}
test_dir = os.path.join(BASE_PATH, "test")
BATCH_SIZE = 32
IMAGE_SIZE = 224
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =======================
# DataLoader
# =======================
test_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
])

test_dataset = datasets.ImageFolder(test_dir, transform=test_transform)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

class_names = test_dataset.classes
num_classes = len(class_names)

# =======================
# Load Models
# =======================
def load_model(model_name, path):
    if model_name == "resnet50":
        model = timm.create_model('resnet50', pretrained=False, num_classes=num_classes)
    elif model_name == "efficientnet_b0":
        model = timm.create_model('efficientnet_b0', pretrained=False, num_classes=num_classes)
    elif model_name == "efficientnet_b3":
        model = timm.create_model('efficientnet_b3', pretrained=False, num_classes=num_classes)
    elif model_name == "densenet121":
        model = timm.create_model('densenet121', pretrained=False, num_classes=num_classes)
    else:
        raise ValueError("Unknown model name")

    state_dict = torch.load(path, map_location=device)
    if isinstance(state_dict, dict) and 'model_state_dict' in state_dict:
        model.load_state_dict(state_dict['model_state_dict'])
    else:
        model.load_state_dict(state_dict)

    model.to(device).eval()
    return model

models = {name: load_model(name, path) for name, path in MODEL_PATHS.items()}

# =======================
# Evaluate & Collect Metrics
# =======================
all_results = []

for model_name, model in models.items():
    print(f"\nEvaluating {model_name}...")
    y_true, y_pred = [], []

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            preds = torch.argmax(outputs, dim=1)
            y_true.extend(labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    report = classification_report(y_true, y_pred, target_names=class_names, output_dict=True, zero_division=0)
    acc = accuracy_score(y_true, y_pred)

    for cls in class_names:
        all_results.append({
            "Model": model_name,
            "Class": cls,
            "Precision": report[cls]['precision'],
            "Recall": report[cls]['recall'],
            "F1-score": report[cls]['f1-score'],
            "Support": report[cls]['support'],
        })

    # Add overall metrics
    all_results.append({
        "Model": model_name,
        "Class": "accuracy",
        "Precision": "",
        "Recall": "",
        "F1-score": "",
        "Support": acc
    })
    for avg in ["macro avg", "weighted avg"]:
        all_results.append({
            "Model": model_name,
            "Class": avg,
            "Precision": report[avg]['precision'],
            "Recall": report[avg]['recall'],
            "F1-score": report[avg]['f1-score'],
            "Support": report[avg]['support']
        })

# =======================
# Save to CSV
# =======================
df = pd.DataFrame(all_results)
csv_path = os.path.join(BASE_PATH, "all_models_detailed_metrics.csv")
df.to_csv(csv_path, index=False)
print(f"\n✅ Detailed metrics saved to: {csv_path}")